name: Playwright Tests for Amazon
on:  #when to trigger the sctions to run the test
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:   #what to test and the setup of software and dependencies
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest. #which os - UBUNTU- - it's a linus os, it provides the safer environment and test runs faster. we can use macos or windows os

    steps:
    -name: Checkout Repository on Github
    uses: actions/checkout@v4
    -name: Setup node.js
    uses: actions/setup-node@v4
    with:
        node-version: lts/*

    -name: Install dependencies
    run: npm ci

    -name: Install Playwright Browsers
    run: npx playwright install --with-deps

    -name: Run Playwright tests
    run: npx playwright test

    -uses: actions/upload-artifact@v4
    if: ${{ !cancelled() }}
    with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
